---
- name: Install Couchbase
  hosts:  all
  become_method: sudo
  tasks:
    - name: Download Couchbase Repo definition
      become: yes
      get_url: dest=/tmp/couchbase-release-1.0-2-x86_64.rpm url=http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-2-x86_64.rpm 

    - name: Install Couchbase Repo definition
      become: yes
      yum: name=/tmp/couchbase-release-1.0-2-x86_64.rpm

    - name: Install Couchbase Server
      become: yes
      yum: name=couchbase-server state=latest
      
    - name: Start Couchbase Server
      become: yes
      service: name=couchbase-server state=started
      
    - name: Wait for Couchbase initialization
      wait_for: port={{ couchbase_port }} delay=2
      
    - name: Check for numactl installed (but do not install it)
      become: yes
      yum:
        list: numactl
      register: numactl_reg
      
    - name: Make data dir... /cbdata
      become: yes
      file: path={{ data_path }} state=directory owner=couchbase group=couchbase mode=u=rwx,g=rx,o=
      
      
    # - name: Update init script with numactl (only if numactl is installed)
    #   become: yes
    #   replace:
    #     dest=/etc/init.d/couchbase-server
    #     regexp='daemon --user couchbase .DAEMON'
    #     replace='daemon --user couchbase "numactl --interleave=all $DAEMON"'
    #   when: (numactl_reg.results|length > 1) and (numactl_reg[1].yumstate == 'installed')
    #
    # - name: Restart Couchbase Server (with numactl)
    #   become: yes
    #   service: name=couchbase-server state=restarted
    #
    # - name: Wait for restarted Couchbase server
    #   wait_for: port={{ couchbase_port }} delay=2